all:
	scons -f ../../../../10-Common/build/SConstruct -I./
Release:
	scons -f ../../../../10-Common/build/SConstruct -I./
Debug:
	scons -f ../../../../10-Common/build/SConstruct -I./ mode=debug
cleanRelease:
	scons -f ../../../../10-Common/build/SConstruct -I./ -c
cleanDebug:
	scons -f ../../../../10-Common/build/SConstruct -I./ mode=debug -c
