from glob import glob
import copy
import os


vc_ver = '10.0'
####### target program name
TargetType = 'lib'   # exe,lib,dll
program_name_release = 'arabcpp'
program_name_debug = copy.copy(program_name_release)

####### lib paths
lib_path_linux_debug = ['../../../../10-Common/lib/debug/linux',]
lib_path_linux_release = ['../../../../10-Common/lib/release/linux',]

lib_path_win32_debug = ['../../../../10-Common/lib/debug/win32',]
lib_path_win32_release = ['../../../../10-Common/lib/release/win32',]

define_macros = []

compile_flags_linux = ['-Werror']

compile_flags_win32 = ['_CONSOLE']
####### include path
include_path = ['../include',
  ]

##ignore warnings generated by these header files
no_warning_include_path = [
  '../../../../10-Common/include',
  '../../../../10-Common/include/cbb/protocol',
  '../../../../10-Common/include/cbb/system',
  ]
####### librarys
## basic libs
libs_kdc_base_debug = []

libs_kdc_base_release = []


## libs that linux only
libs_kdc_linux_debug = copy.copy(libs_kdc_base_debug)

libs_kdc_linux_release = copy.copy(libs_kdc_base_release)

## libs that win32 only
libs_kdc_win32_base = []
libs_kdc_win32_debug = copy.copy(libs_kdc_base_debug)
libs_kdc_win32_debug.extend(libs_kdc_win32_base)

libs_kdc_win32_release = copy.copy(libs_kdc_base_release)
libs_kdc_win32_release.extend(libs_kdc_win32_base)

###### source files
def files_finder(path):
  return glob(path.replace('/',os.sep))
source_files = files_finder('../src/*.cpp')
source_files += files_finder('../src/*.cc')
install_dir_base = '../../../../10-Common/lib/'
install_dir_linux_debug = install_dir_base + "debug/linux/"
install_dir_linux_release = install_dir_base + "release/linux/"
install_dir_win32_debug = install_dir_base + "debug/win32/"
install_dir_win32_release = install_dir_base + "release/win32/"
